In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train) #CADA COLUMNA SERA UN ATRIBUTO

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos: normalización. 
normalizer = preprocessing.MinMaxScaler() #HACE LA RESTA DEL MAXIMO MENOS MIN
X_train_norm = normalizer.fit_transform(X_train) 
# .fit : extraer inf de los datos para hacer la normalizacion
# .fit_transform busca los estadisticos a partir de la matriz y los transforma
# .transform : se asume que ya tiene los estadisticos -> solo se aplica el algoritmo

In [4]:
# Salida de resultados.
print(X_train_norm) #valor min es 0 y el max es 1, luego ya esta normalizado

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
import pandas as pd
df = pd.DataFrame({ 'Método': ['.fit()','.fit_transform()', '.transform()'], 'Dónde se usa':['Datos de Entrenamiento', 'Datos de Entrenamiento', 'Datos de Prueba'], 'Propósito': ["Calcular parámetros (μ, σ, min, max).", 'Calcular parámetros y aplicarlos inmediatamente.', 'Aplicar los parámetros calculados en el entrenamiento a datos desconocidos.']})
display(df)

,Método,Dónde se usa,Propósito
0,.fit(),Datos de Entrenamiento,"Calcular parámetros (μ, σ, min, max)."
1,.fit_transform(),Datos de Entrenamiento,Calcular parámetros y aplicarlos inmediatamente.
2,.transform(),Datos de Prueba,Aplicar los parámetros calculados en el entren...


In [6]:
# #lo aporto yo
# from sklearn.preprocessing import StandardScaler
# import numpy as np

# # Datos de entrenamiento (Train) y de prueba (Test)
# X_train = np.array([[1.60], [1.70], [1.80], [1.90]])
# X_test = np.array([[1.65], [1.85]])

# scaler = StandardScaler()

# # PASO 1: fit_transform en Entrenamiento
# # Aquí el scaler calcula que la media es 1.75 (fit) y luego escala los datos (transform)
# X_train_scaled = scaler.fit_transform(X_train)

# # PASO 2: transform en Prueba
# # ¡IMPORTANTE! Aquí no usamos fit. Usamos la media de 1.75 que ya conocemos 
# # para transformar los datos de prueba.
# X_test_scaled = scaler.transform(X_test)

# #¿Por qué no hacer .fit() en los datos de prueba? 
# #Si haces un nuevo .fit() en los datos de prueba, estarías calculando una nueva media basada solo en esos pocos datos. Esto se conoce como Data Leakage (fuga de datos), 
# #ya que estarías introduciendo información del futuro o sesgando la escala, lo que causará que las predicciones de tu modelo sean erróneas o inconsistentes.                                

In [13]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train_2)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

#hacer el fit_transform es lo mismo que hacer primero el fit y luego el transform

True


### EJERCICIO

In [14]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])

# Normalizar los datos de "X_test"
# ???
# X_test_norm = normalizer.fit_transform(X_test)  ESTA OPCION MEJOR NO
X_test_norm = f.transform(X_test) #dado que la f la tenemos guardada mas arriba

print(X_test_norm)
# print(X_test_norm_2) #son iguales ambos

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


Este archivo es un cuaderno de Jupyter centrado en la **normalización de datos** utilizando la librería `scikit-learn`. El objetivo principal es enseñar cómo escalar datos numéricos para que un modelo de Machine Learning pueda procesarlos mejor, y explicar la diferencia crucial entre los métodos `fit`, `transform` y `fit_transform`.

Aquí tienes el desglose de lo que sucede en el código:

---

## 1. ¿Qué es la Normalización?

En el código se utiliza `MinMaxScaler`. Este proceso transforma los datos para que todos los valores queden en un rango específico, generalmente **entre 0 y 1**.

* El **0** representa el valor mínimo de esa columna.
* El **1** representa el valor máximo.

## 2. Los Conceptos Clave (La "Regla de Oro")

El archivo incluye una tabla muy útil que resume cuándo usar cada método:

| Método | Dónde se usa | Propósito |
| --- | --- | --- |
| **`.fit()`** | Datos de Entrenamiento | Calcula los parámetros (como el mínimo y el máximo). |
| **`.fit_transform()`** | Datos de Entrenamiento | Hace el cálculo y escala los datos al mismo tiempo. |
| **`.transform()`** | Datos de Prueba (Test) | Aplica la escala calculada previamente a datos nuevos. |

> **Nota importante sobre el "Data Leakage":** El código advierte que **nunca** se debe usar `.fit()` en los datos de prueba. Si calculas un nuevo máximo y mínimo para el test, estarías "engañando" al modelo con información que no debería conocer, lo que causaría errores en las predicciones.

---

## 3. Flujo del Código

1. **Carga:** Se crea una matriz `X_train` con valores desordenados (desde -4 hasta 6).
2. **Entrenamiento:** Se usa `MinMaxScaler().fit_transform(X_train)` para que el programa "aprenda" cuál es el rango de esos datos y los convierta a la escala 0-1.
3. **Validación:** El código demuestra que hacer `.fit_transform()` es exactamente lo mismo que hacer `.fit()` y luego `.transform()` por separado.
4. **Aplicación (Ejercicio):** Se crean datos nuevos (`X_test`). Para normalizarlos, **solo** se usa `.transform()`, aplicando los parámetros que aprendimos del grupo anterior.

## 4. Ejemplo Visual

Si tus datos originales en una columna son `[1, 5, 0]`:

* El **0** se convierte en `0.0`.
* El **5** (el máximo) se convierte en `1.0`.
* El **1** se convierte en `0.2`.



Esa es una excelente pregunta. La clave está en cómo funciona la **Programación Orientada a Objetos** en Python y cómo `scikit-learn` guarda la información internamente.

Aquí te explico por qué `f` ya sabe qué hacer:

### 1. El momento del "aprendizaje"

En la celda 13 de tu cuaderno, ejecutas esta línea:
`f = normalizer.fit(X_train)`

Cuando llamas al método **`.fit()`**, el objeto `normalizer` analiza la matriz `X_train` y calcula los valores estadísticos necesarios (en este caso, el valor **mínimo** y el **máximo** de cada columna).

### 2. La variable `f` es una referencia

Al hacer `f = normalizer.fit(...)`, la variable `f` no es solo un resultado, sino que apunta al objeto `normalizer` que ya ha sido "entrenado".

* **¿Qué guarda `f` por dentro?** Guarda los parámetros calculados (como `data_min_` y `data_max_`).
* **¿Por qué es útil?** Porque ahora `f` tiene la "receta" exacta para transformar cualquier dato futuro usando la misma escala que usó con los datos de entrenamiento.

### 3. El peligro de no usar `f`

Como bien indica el comentario en tu código, si en lugar de usar `f.transform(X_test)` usaras `fit_transform(X_test)`, estarías calculando **nuevos** mínimos y máximos basados en los datos de prueba.

Esto es un error grave llamado **Data Leakage** (fuga de datos) porque:

* Tus datos de prueba se escalarían de forma distinta a los de entrenamiento.
* Estarías dándole al modelo información "del futuro" o sesgada, lo que haría que tus predicciones fueran inconsistentes.

---

**Resumen:** `f` ya está entrenado porque el método `.fit()` extrajo la información estadística de `X_train` y la dejó almacenada permanentemente dentro del objeto al que `f` hace referencia.
