In [1]:
import numpy as np
from sklearn import datasets
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [9]:
# Carga de datos
iris = datasets.load_iris()
#print(iris) #tenemos una serie de atributos
#los datos son: 4 caracteristicas
#print(iris['data'].shape) #150 muestras con 4 atributos
#print(iris.keys()) 
#print(iris['target']) #para ver las etiquetas
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [12]:
# Mostrar características de la tabla de datos.
print("Tabla de datos: %d instancias y %d atributos" % (iris.data.shape[0], iris.data.shape[1])) #para ver el numero de filas y n de colums
print("Valores de la clase:", set(iris.target)) #posibles valores de la variable objetivo

# Cuantificamos el número de instancias que contiene el dataset por clase
valores, ocurrencias = np.unique(iris.target, return_counts=True) #el n de muestras de cada clase
print(valores, ocurrencias) #+ porcentaje que podriamos sacar de cada ocurrencia, siendo balanceado, pq tienen igual proporcion en todas las categorias

Tabla de datos: 150 instancias y 4 atributos
Valores de la clase: {np.int64(0), np.int64(1), np.int64(2)}
[0 1 2] [50 50 50]


In [13]:
# Test: hold-out split 80-20%. # Partición externa
X_training, X_test, y_training, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
valores_test, ocur_test = np.unique(y_test, return_counts=True)
print('Test: ', 'clases:', valores_test, ' ocurrencias: ', ocur_test)

Test:  clases: [0 1 2]  ocurrencias:  [10  9 11]


In [15]:
# Estandarizar las características de entrenamiento y de test, antes de entrenar los modelos
standardizer = StandardScaler()
X_training = standardizer.fit_transform(X_training)
X_test = standardizer.transform(X_test) #asumiendo que solo tenemos acceso a los datos de entrenamientos para ajustar las distintas tareas

In [17]:
# Validación: hold-out split 80-20%. # Partición interna
X_train, X_val, y_train, y_val = train_test_split(X_training, y_training, test_size=0.2, random_state=42)
valores_train, ocur_train = np.unique(y_train, return_counts=True)
print('Entrenamiento: ', ' clases:', valores_train, '  ocurrencias:', ocur_train)

valores_val, ocur_val = np.unique(y_val, return_counts=True)
print('Validation:    ', ' clases:', valores_val, '  ocurrencias:', ocur_val)

#esto que se ha hecho no es del todo correcto:
# standardizer.fit_transform(X_training) lo hemos ajustado sobre todos los datos de entrenamiento
#sin embargo : luego hemos hecho una particion de X_train, X_val, y_train, y_val
# entonces el proceso de validacion ya va a estar ligeramente sesgado, lo que quiere decir, que al haber usado tandardizer.fit_transform(X_training) deberiamos haber usado x_train

Entrenamiento:   clases: [0 1 2]   ocurrencias: [32 30 34]
Validation:      clases: [0 1 2]   ocurrencias: [ 8 11  5]


In [18]:
#TAREA: 

# 1. Primero realizamos la partición de los datos (Hold-out 80-20%)
# Esto asegura que el conjunto de validación sea independiente desde el inicio
X_train, X_val, y_train, y_val = train_test_split(X_training, y_training, test_size=0.2, random_state=42)

# 2. Inicializamos el estandarizador
standardizer = StandardScaler()

# 3. AJUSTE (Fit) y TRANSFORMACIÓN: Solo sobre el conjunto de TRAIN
# Calculamos media y desviación típica solo con los datos de entrenamiento interno
X_train = standardizer.fit_transform(X_train)

# 4. TRANSFORMACIÓN: Aplicamos el ajuste previo a Validación y Test
# Usamos solo .transform() para no "aprender" nada de estos conjuntos
X_val = standardizer.transform(X_val)
X_test = standardizer.transform(X_test) 

# Comprobación de coherencia de las clases
valores_train, ocur_train = np.unique(y_train, return_counts=True)
print('Entrenamiento: ', ' clases:', valores_train, ' ocurrencias:', ocur_train)

valores_val, ocur_val = np.unique(y_val, return_counts=True)
print('Validación:    ', ' clases:', valores_val, ' ocurrencias:', ocur_val)

Entrenamiento:   clases: [0 1 2]  ocurrencias: [32 30 34]
Validación:      clases: [0 1 2]  ocurrencias: [ 8 11  5]


In [24]:
# Construcción del objeto que contiene el algoritmo de aprendizaje.
clf = DummyClassifier(strategy='prior', random_state=42)

In [25]:
# Entrenamiento del algoritmo de aprendizaje.
clf = clf.fit(X_train, y_train)

In [29]:
preds_val = clf.predict_proba(X_val)
print(preds_val) #nos devuelve un score de probabilidad

[[0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]
 [0.33333333 0.3125     0.35416667]]


In [22]:
# Evaluación del algoritmo de aprendizaje con el método "score" que devuelve directamente la métrica de 'accuracy'
val_accuracy = clf.score(X_val, y_val)
print("Exactitud en validación: ", val_accuracy)

test_accuracy = clf.score(X_test, y_test)
print("Exactitud en test: ", test_accuracy)

Exactitud en validación:  0.20833333333333334
Exactitud en test:  0.36666666666666664


In [30]:
# Obtenemos las predicciones sobre conjunto de validación y de test
y_pred_val = clf.predict(X_val)
print('Predicciones de validación ', y_pred_val)
print('Etiquetas reales validación', y_val)

y_pred_test = clf.predict(X_test)
print('\nPredicciones de test ', y_pred_val)
print('Etiquetas reales test', y_val)

Predicciones de validación  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
Etiquetas reales validación [1 1 0 0 0 2 1 2 2 2 1 1 1 1 1 0 2 0 1 0 1 1 0 0]

Predicciones de test  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
Etiquetas reales test [1 1 0 0 0 2 1 2 2 2 1 1 1 1 1 0 2 0 1 0 1 1 0 0]


In [31]:
# Aplicamos un ejemplo con un clasificador más complejo que el "dummyclassifier"
from sklearn.svm import SVC #esto es un modelo q ya veremos mas adelante
svc = SVC(C=0.5) # Definimos algoritmo
svc.fit(X_train, y_train) # Entrenamos modelo

val_accuracy = svc.score(X_val, y_val) # Evaluamos modelo en validación
print('Exactitud en validación ', np.round(val_accuracy*100, 4), '%')

test_accuracy = svc.score(X_test, y_test) # Evaluamos modelo en test
print('Exactitud en test ', np.round(test_accuracy*100, 4), '%')

Exactitud en validación  91.6667 %
Exactitud en test  96.6667 %


In [40]:
#primero creamos la carperta
import os

# Definimos la ruta relativa (subir un nivel y entrar en models)
ruta_carpeta = '../models'

# Creamos la carpeta si no existe para evitar el error de Python
if not os.path.exists(ruta_carpeta):
    os.makedirs(ruta_carpeta)
    print(f"Carpeta creada en: {os.path.abspath(ruta_carpeta)}")

In [43]:
import pickle

# 1. Guardar el modelo
with open('../models/model.pickle', 'wb') as fw:
    pickle.dump(svc, fw) #en vez de model, ponemos svc que es como esta guarado el modelo

# 2. Guardar el estandarizador (¡Muy importante!)
# Sin esto, no podrás procesar correctamente los datos nuevos en la fase de explotación
with open('../models/standardizer.pickle', 'wb') as fs:
    pickle.dump(standardizer, fs) 

print("Arquitectura de modelo y preprocesado guardada correctamente.")

Arquitectura de modelo y preprocesado guardada correctamente.


Este cuaderno de Jupyter explica la técnica de **Hold-Out**, que es el método fundamental para evaluar modelos de Machine Learning dividiendo el conjunto de datos en subgrupos independientes.

Aquí tienes el desglose de los conceptos y pasos clave realizados en el código:

---

## 1. El Dataset: Iris

Se utiliza el famoso dataset **Iris**, que contiene 150 instancias (muestras) de flores divididas equitativamente en 3 clases (50 muestras de cada una): **Setosa**, **Versicolor** y **Virginica**. Cada muestra tiene 4 atributos físicos (ancho y largo de sépalo y pétalo).

## 2. La Triple Partición (Hold-Out)

El código enfatiza la importancia de dividir los datos en tres conjuntos para garantizar una evaluación justa:

* **Entrenamiento (Train):** Datos usados para que el modelo aprenda los patrones.
* **Validación (Val):** Datos usados para ajustar los hiperparámetros del modelo y comparar diferentes algoritmos sin "quemar" el conjunto de test.
* **Prueba (Test):** El examen final. Datos que el modelo jamás ha visto y que sirven para medir su rendimiento real en el mundo exterior.

---

## 3. Evitando el Sesgo: El Orden Importa

Un punto crítico que resalta el cuaderno es el orden del preprocesado (estandarización):

1. **Primero se divide:** Se separan los datos en Train, Val y Test.
2. **Luego se ajusta el escalador:** Se usa `standardizer.fit_transform()` **solo** en el conjunto de entrenamiento.
3. **Finalmente se transforma:** Se usa `.transform()` en Validación y Test usando los parámetros (media y desviación) aprendidos del entrenamiento.

> Si ajustas el estandarizador con todos los datos antes de dividir, cometes **Data Leakage**, ya que el entrenamiento "sabría" cosas sobre la distribución de los datos de test.

---

## 4. Clasificadores Utilizados

* **DummyClassifier:** Un modelo básico que sirve como línea base (baseline). En este caso, usa la estrategia 'prior', que simplemente predice siempre la clase más frecuente. Por eso sus predicciones son todas iguales (clase 2) y su exactitud es baja (~20-36%).
* **SVC (Support Vector Classifier):** Un modelo mucho más potente que logra una exactitud cercana al 91-96%.

---

## 5. Exportación del Modelo

Al final, el código utiliza la librería `pickle` para guardar dos archivos esenciales para la fase de producción:

* `model.pickle`: El cerebro del modelo ya entrenado.
* `standardizer.pickle`: El escalador. **Es vital guardarlo**, porque cualquier dato nuevo que llegue en el futuro debe ser transformado exactamente con la misma escala que se usó durante el entrenamiento.
